spring.application.name=logincompleto

spring.config.import=optional:file:.env[.properties]

spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=loginseguro

spring.data.mongodb.auto-index-creation=true

# nome do arquivo CSS existente em static/css/temas, sem a extensão
app.tema=escuro